name: Curl Request

on:
  schedule:
    - cron: '*/10 * * * *'  # Schedule to run every 10 minutes

jobs:
  curl_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Curl Request
        run: curl --location 'https://app.shubhasaimohapatra.in/projects' --data ''
